#!/bin/sh
cd ../se/frontend/app/ # cd to the base front end directory.
rm -rf node_modules/ # Remove the node_modules folder for a clean install.
rm -rf .yarnclean # Remove the .yarnclean log, because it prevents yarn build from completing locally.
rm -rf build/ # Remove the old build folder (front end) if one exists so the newly installed can be copied from the Docker image.
cd ../../backend/app/ # cd to the base back end directory.
rm -rf build/ # Remove the old build folder (back end) if one exists so the newly installed can be copied from the front end directory.
rm -rf static/ # Remove the old build folder (back end) if one exists so the newly installed can be copied from the front end directory.
exit 0 # Exit with no error.
